steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - jovita-bot-service/Dockerfile
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
substitutions:
  _IMAGE: us-central1-docker.pkg.dev/$PROJECT_ID/ctw2026/jovita:latest
